name: Pipeline Big Data - EA1, EA2 y EA3

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-full-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositorio
      uses: actions/checkout@v4

    - name: Configurar Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar Dependencias
      run: |
        pip install --upgrade pip
        pip install -e .

    - name: Ejecutar Actividad 1 - Ingesta de Datos
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        python src/ingestion.py

    - name: Ejecutar Actividad 2 - Limpieza y Procesamiento
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        python src/processing.py

    - name: Ejecutar Actividad 3 - Enriquecimiento de Datos
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        python src/enrichment.py

    - name: Subir Evidencias y Artefactos de las 3 Actividades
      uses: actions/upload-artifact@v4
      with:
        name: evidencias-pipeline-bigdata
        path: |
          src/xlsx/ingestion.xlsx
          src/xlsx/cleaned_data.xlsx
          src/xlsx/enriched_data.xlsx
          src/static/auditoria/ingestion.txt
          src/static/auditoria/cleaning_report.txt
          src/static/auditoria/enriched_report.txt