name: Pipeline Big Data Ingesta y Limpieza

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .

    - name: Run Ingestion (Actividad 1)
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        python src/ingestion.py

    - name: Run Processing and Cleaning (Actividad 2)
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        python src/processing.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: evidencias
        path: |
          src/xlsx/ingestion.xlsx
          src/xlsx/cleaned_data.xlsx
          src/static/auditoria/ingestion.txt
          src/static/auditoria/cleaning_report.txt